language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- "./build/build-and-test.sh"
install: true
deploy:
  provider: "heroku"
    api_key:
      secure: "e25WT56DANhZqcmFXXpTKH2Xy13437L6huaC1PtKb/ykArxBf8egFglt5H8hvhujAGVyv/05S+7neJB1S9fn8VylFsf3WundAjsiOtnsap/DrtTcL75TrL3rvvdKQHal66mcLXGe4GkxTAPhoWxYC2o+hOzCU3r/dxUb7eJGH/W2REZ6C3uigbVQV3m+PTzo1VOaTgmJVZIomr5G5xAPJiJxynL+FrkOWxAZa0jmNFzbqU/gdcDilmIZNUBmI2n4dMm/Ff3RraUCe6J/qGWotGyVBeAi/eCa9xQ+5/MAaPIifxDe57pOhQfa3ieMLC2XgkN7EnAubQEqUoGTygIpLMsZa55yFJuUa0HX7PQZ9QkjcrrXlbkrv59fy4E1JS6SpquKIdS4BumxCbEzXcRRYpbxtpGRGrdiDxyGx6mrHVjiCJCIkmM4mBr1Qo/uvJ/HheEI7TKH0tsQLxq6FgVGbYunwgU1ojuRHQne8ORTHvXAOInmObc/hO+GVWikL+cwhTjVeU9T0VqT5nB9jTiQP4bOOZqjRcaET0kzDFEBZjA9abH/LqNmgWAV8R9hBDplqpJhBbjwhDyoWoGEO0cZUogrjoqMYtkLusu+Ctt3R/xI7ahthdKrxb2mCmKrgAuxakMn++WZS/cuppYvW4dRumlN6abRavIwggkuazQZIVY="
    app: mia-jdjobs-dev
